name: Code Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Install `pre-commit`
        run: pip install pre-commit

      - name: Install TFLint
        run: curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Install `pre-commit` hooks
        run: pre-commit install

      - name: Run `pre-commit` checks
        run: pre-commit run --all-files
